#!/bin/bash


# Monitor
bspc monitor -d 1 2 3 4 5             # Workspace tag names (needs to be the same as the polybar config to work)

# Window Information
bspc config border_width      3
bspc config window_gaps      12
bspc config split_ratio     0.5

bspc config click_to_focus           true
bspc config focus_follows_pointer    false
bspc config borderless_monocle       false
bspc config gapless_monocle          false

#bspc config normal_border_color  "#000000"
#bspc config focused_border_color "#ffffff"


# Rules
bspc rule -r '*'
bspc rule -a '*:*:Picture in picture' 'state=floating' 'sticky=on'
bspc rule -a '*:*:Picture-in-Picture' 'state=floating' 'sticky=on'
bspc rule -a '.blueman-manager-wrapped' 'state=floating' 'sticky=on'
bspc rule -a 'Emacs' 'desktop=3' 'follow=on' 'state=tiled'
bspc rule -a 'Lutris' 'desktop=5' 'follow=on'
bspc rule -a 'Pavucontrol' 'state=floating' 'sticky=on'
bspc rule -a 'Pcmanfm' 'state=floating'
bspc rule -a 'Steam' 'desktop=5'
bspc rule -a 'libreoffice' 'desktop=3' 'follow=on'
bspc rule -a 'plexmediaplayer' 'desktop=4' 'follow=on' 'state=fullscreen'

# java gui fixes
export _JAVA_AWT_WM_NONREPARENTING=1
bspc rule -a sun-awt-X11-XDialogPeer state=floating

# Startup
feh --bg-scale $HOME/.config/wall     # Wallpaper

#pgrep -x sxhkd > /dev/null || sxhkd &

killall -q polybar &                  # Reboot polybar to correctly show workspaces
while pgrep -u $UID -x polybar >/dev/null; do sleep 1;done 

polybar main & #2>~/log &             # To lazy to figure out systemd service order

if [[ $(xrandr -q | grep 'DisplayPort-1 connected') ]]; then   # If second monitor, also enable second polybar
  bspc monitor DP1 -d 6 7 8 9 10
  bspc wm -O HDMI3 DP1
  polybar sec &
fi


