#!/bin/sh

# Monitor
bspc monitor -d 1 2 3 4 5 

# Window Information
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

# Rules
bspc rule -r '*'
bspc rule -a 'Emacs' 'desktop=^3' 'follow=on' 'state=tiled'
bspc rule -a 'Firefox' 'desktop=^2'
bspc rule -a 'Google-chrome' 'desktop=^2'
bspc rule -a 'Pcmanfm' 'state=floating'
bspc rule -a 'plexmediaplayer' 'desktop=^5' 'state=fullscreen'

# Startup

#pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-scale $HOME/.config/wall

killall -q polybar &                                # Reboot polybar to correctly show workspaces
sleep 0.5; polybar top & #2>~/log &                 # To lazy to figure out systemd service order
