#!/bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
#pkill picom
#picom --experimental-backends &
#feh --bg-fill ~/...
#~/.config/polybar/launch.sh

# Monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Window Information
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
