#!/bin/sh

# Monitor
bspc monitor -d 1 2 3 4 5 

# Window Information
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Startup
killall -q polybar &						# Reboot polybar to correctly show workspaces
sleep 0.5; polybar top & #2>~/log &				# To lazy to figure out systemd service order
