#! /usr/bin/env zsh

# PATH
export PATH=/run/current-system/sw/bin:/opt/homebrew/bin:$PATH

# Defaults
export SHELL=zsh
export EDITOR='nvim'
export DEFAULT_USER=tom
export WLR_DRM_NO_MODIFIERS=1
# Directory Env Vars
export GOPATH=$HOME/go
export GOBIN=$HOME/go/bin
export DOCKER_HOST="unix://$HOME/.colima/default/docker.sock"

# Google Cloud GKE
export USE_GKE_GCLOUD_AUTH_PLUGIN=True

export KUBECONFIG=$HOME/.kube/config

# set virtualenvwrapper to global python3
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3

# SSH
export SSH_KEY_PATH="~/.ssh/id_ed25519"

# COSIGN
export CK=$HOME/.cosign/cosign.key
export CP=$HOME/.cosign/cosign.pub

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# use ripgrep for fzf
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'

# That stupid thing I need for GPG
export GPG_TTY=$(tty)

