#!/usr/bin/env bash

# like cd but fuzzy
cf() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune \
                  -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir" || return
}

# sync caravan repo
push-nix() {
    cd ~/.config/nixpkgs
    git add .
    git commit -a -m "$1"
    git push
    cd -
  }

sync-nix() {
    cd ~/.config/nixpkgs
    git add .
    git stash
    git checkout main
    git pull origin main
    git stash pop
    home-manager switch
    push-nix "sync-nix performed on $(date)"
    cd -
}

kc-patch-secret() {
  local value
  value=$(echo "$3" | base64)
  kubectl patch secret "$1" --type='json' -p='[{"op" : "replace" ,"path" : '$2' ,"value" : '$value'}]'
}

kc-decode-secret() {
  local value
  value=$(kubectl get secret "$1" -o jsonpath="{$2}")
  echo "$value" | base64 -d
}

gitra() {
  url="git@github.com:$1/$2.git"
  git remote add $1 $url
}

gcloud-auth() {
  gcloud init
  gcloud auth login
  gcloud auth application-default login
  gcloud auth configure-docker us-central1-docker.pkg.dev,asia-northeast1-docker.pkg.dev,europe-west1-docker.pkg.dev
}

new-cosign-image() {
  docker pull $1
  docker tag $1 $2/$1
  docker push $2/$1
  cosign attest --predicate $HOME/.tmp/cosign/predicate.json --type custom $2/$1 --key $CK 
}
