#!/usr/bin/env sh

source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
DYNAMIC_ISLAND_DIR="$HOME/.config/sketchybar/plugins/Dynamic-Island-Sketchybar"

# I don't have SIP disabled
# SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components

# Define Dynamic island custom configs here
source "$DYNAMIC_ISLAND_DIR/config.sh" # Loads Dynamic-Island config

# helper process
HELPER=git.felix.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

ISLANDHELPER=git.crissnb.islandhelper
killall islandhelper
cd $DYNAMIC_ISLAND_DIR/helper && make
$DYNAMIC_ISLAND_DIR/helper/islandhelper $ISLANDHELPER &

FONT="JetBrainsMono Nerd Font"

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration ITEMe see my dotfiles:
# https://github.com/FelixKratz/dotfiles

BACKGROUND="0xff2f343f"
FOREGROUND="0xffDB686B"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
  height=50 
  position=top     
  notch_width=188
  sticky=off       
  pading_left=10  
  padding_right=10
  color=0x00000000
)

sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  icon.font="$FONT:Regular:15.0"
  icon.color="0xffAFDCA4"
  label.font="$FONT:Regular:15.0"
  label.color="0xffAFDCA4"
  padding_left=5
  padding_right=5
  label.padding_left=4
  label.padding_right=4
  icon.padding_left=4
  icon.padding_right=4
  y_offset=5
  background.height=30
)

sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Now we add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces

SPACE_ICONS=("" "" "󰈹" "󰒱" "󰆟" "" "" "󰁥" "" "󰆟")

spaces=()
for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))
  spaces+=(space.$sid)
  sketchybar --add space space.$sid left                                 \
             --set space.$sid associated_space=$sid                      \
                              icon=${SPACE_ICONS[i]}                     \
                              background.corner_radius=8                 \
                              background.color=0x30ffffff               \
                              background.drawing=off                     \
                              label.drawing=off                          \
                              script="$ITEM_DIR/space.sh"              \
                              click_script="yabai -m space --focus $sid"
done


##### Adding Left Items #####
# We add some regular items to the left side of the bar
# only the properties deviating from the current defaults need to be set

sketchybar --add item space_separator left                         \
           --set space_separator icon=                            \
                                 padding_left=10                   \
                                 label.drawing=off                 \
                                 icon.color="0xffCFD6F1" \
                                                                   \
           --add item front_app left                               \
           --set front_app       script="$ITEM_DIR/front_app.sh" \
                                 icon.drawing=off                  \
                                 background.color="$BACKGROUND"    \
                                 label.color="0xffCFD6F1" \
           --subscribe front_app front_app_switched

sketchybar --add bracket spaces "${spaces[@]}" space_separator front_app \
           --set spaces background.color=$BACKGROUND \
                        background.corner_radius=8   \

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right                              \
           --set clock   update_freq=10                        \
                         icon=󰅐                                \
                         script="$ITEM_DIR/clock.sh"         \
                         background.color="$BACKGROUND"        \
                         background.corner_radius=8            \
                         label.color="0xffDB686B" \
                         icon.color="0xffDB686B" \
                                                               \
           --add item wifi right                               \
           --set wifi    script="$ITEM_DIR/wifi.sh"          \
                         icon=󰖩                                \
                         background.color="$BACKGROUND"        \
                         background.corner_radius=8            \
                         label.color="0xffF19B53" \
                         icon.color="0xffF19B53" \
           --subscribe wifi wifi_change                        \
                                                               \
           --add item battery right                            \
           --set battery script="$ITEM_DIR/battery.sh"       \
                         update_freq=120                       \
                         background.color="$BACKGROUND"        \
                         background.corner_radius=8            \
                         label.color="0xffBB7CD7" \
                         icon.color="0xffBB7CD7"
           --subscribe battery system_woke power_source_change

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

source "$DYNAMIC_ISLAND_DIR/item.sh" # Loads Dynamic-Island item

sketchybar --update

