#
# Hardware settings for Dell XPS 15 9500
# Dual boot active. Windows @ nvme0n1p3 / NixOS @ nvme0n1p7
#
# flake.nix
#  └─ ./hosts
#      └─ ./xps
#          ├─ default.nix
#          └─ hardware-configuration.nix *
#
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#

{ config, lib, pkgs, modulesPath, host, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5701437d-9ca9-4f6b-bae3-d5a51a9b5dc9";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/44AF-9E34";
      fsType = "vfat";
    };

  swapDevices = [ ];

  networking = with host; {
    useDHCP = lib.mkDefault true;
  # interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;
    hostName = hostName;
    enableIPv6 = false;
    networkmanager = {
      enable = true;
      extraConfig = ''
        [main]
        rc-manager=resolvconf
      '';
    };
    nameservers = [ "192.168.0.4" "1.1.1.1"];
    firewall.enable = false;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
