#!/bin/sh

VOL=$(amixer get Master | tail -n1 | awk -F ' ' '{print $5}' | tr -d ' [%]')

get_volume_icon() {
  if [[ $VOL -ge 75 ]]; then
    printf " $VOL"
  elif [[ $VOL -lt  75 && $VOL -gt 25 ]]; then
    printf " $VOL"
  elif [[ $VOL -lt  25 ]]; then
    printf " $VOL"
  else
    printf ""
  fi
}
get_volume_icon
