#!/bin/sh

for cap in /sys/class/power_supply/hid-dc:2c:26:36:79:9b-battery/capacity; do
  BATT=$(cat "$cap")
done
for stat in /sys/class/power_supply/hid-dc:2c:26:36:79:9b-battery/status; do
  STAT=$(cat "$stat")
done

case "$STAT" in
  "Charging" ) printf "󰌌  $BATT%%";;
  "Full" ) printf "󰌌  Full";;
  "Discharging" ) printf "󰌌 $BATT%%";;
  * ) echo "";
esac
