#!/bin/sh

SINK=$(pactl info | grep 'Default Sink' | cut -d':' -f 2)
SINK=${SINK// /}

HEAD=$(eww get headphones)
SPEAK=$(eww get speaker)

case "$SINK" in
	"$HEAD" ) printf "󰋋";;
	"$SPEAK" ) printf "󰓃";;
	* ) printf "";;
esac
