#!/bin/sh

ws=(1 2 3 4 5 6 7 8 )

workspaces() {
	unset -v \
	o1 o2 o3 o4 o5 o6 o7 o8 \
	f1 f2 f3 f4 f5 f6 f7 f8

	# occupied workspaces
	ows="$(hyprctl workspaces -j | jq '.[] | del(select(.id == -99)) | .id')"

	for num in $ows; do
		export o"$num"="$num"
	done

	# focused workspaces
	mon="$1"
	num="$(hyprctl monitors -j | jq --argjson arg "$mon" '.[] | select(.id == $arg).activeWorkspace.id')"
	export f"$num"="$num"

	# alt (button :onclick \"hyprctl dispatch workspace 1\" :class \"w0$o1$f1\" \"${ws[o]} ₁\")
	if [ "$1" = 1 ]; then
		echo "(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
		        (box :class \"workspace\" :orientation \"h\" :space-evenly \"false\" 	\
		          (button :onclick \"hyprctl dispatch workspace 1\" :class \"w0$o1$f1\" \"${ws[0]}\") \
		          (button :onclick \"hyprctl dispatch workspace 2\" :class \"w0$o2$f2\" \"${ws[1]}\") \
		          (button :onclick \"hyprctl dispatch workspace 3\" :class \"w0$o3$f3\" \"${ws[2]}\") \
		          (button :onclick \"hyprctl dispatch workspace 4\" :class \"w0$o4$f4\" \"${ws[3]}\")))"
	elif [ "$1" = 0 ]; then
		echo "(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
		        (box :class \"workspace\" :orientation \"h\" :space-evenly \"false\" 	\
		          (button :onclick \"hyprctl dispatch workspace 5\" :class \"w0$o5$f5\" \"${ws[4]}\") \
		          (button :onclick \"hyprctl dispatch workspace 6\" :class \"w0$o6$f6\" \"${ws[5]}\") \
		          (button :onclick \"hyprctl dispatch workspace 7\" :class \"w0$o7$f7\" \"${ws[6]}\") \
		          (button :onclick \"hyprctl dispatch workspace 8\" :class \"w0$o8$f8\" \"${ws[7]}\")))"
	fi
}

workspaces $1
socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r; do 
workspaces $1
done
