#!/bin/sh

ws=(1 2 3 4 5 6 7 8 9)

workspaces() {
	unset -v \
	o1 o2 o3 o4 o5 o6 o7 o8 o9 \
	f1 f2 f3 f4 f5 f6 f7 f8 f9

	# occupied workspaces
	ows="$(hyprctl workspaces -j | jq '.[] | del(select(.id == -99)) | .id')"

	for num in $ows; do
		export o"$num"="$num"
	done

	# focused workspaces
	act="$1"
	num="$(hyprctl monitors -j | jq --argjson arg "$act" '.[] | select(.id == $arg).activeWorkspace.id')"
	export f"$num"="$num"

	# monitors
	mon="$(hyprctl monitors | grep ID | wc -l)"


	eb="(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
      (box :class \"workspace\" :orientation \"h\" :space-evenly \"false\""
	wsm1="(button :onclick \"hyprctl dispatch workspace 1\" :class \"w0$o1$f1\" \"${ws[0]}\") \
      (button :onclick \"hyprctl dispatch workspace 2\" :class \"w0$o2$f2\" \"${ws[1]}\") \
      (button :onclick \"hyprctl dispatch workspace 3\" :class \"w0$o3$f3\" \"${ws[2]}\") \
      (button :onclick \"hyprctl dispatch workspace 4\" :class \"w0$o4$f4\" \"${ws[3]}\")"
	wsm2="(button :onclick \"hyprctl dispatch workspace 5\" :class \"w0$o5$f5\" \"${ws[4]}\") \
      (button :onclick \"hyprctl dispatch workspace 6\" :class \"w0$o6$f6\" \"${ws[5]}\") \
      (button :onclick \"hyprctl dispatch workspace 7\" :class \"w0$o7$f7\" \"${ws[6]}\") \
      (button :onclick \"hyprctl dispatch workspace 8\" :class \"w0$o8$f8\" \"${ws[7]}\")"
#wsm3="(button :onclick \"hyprctl dispatch workspace 9\" :class \"w0$o9$f9\" \"${ws[8]}\")"


	# set workspaces depending on how many active monitors
	if [ "$mon" -eq "1" ]; then
		echo "$eb$wsp1$wsp2))"
	elif [ "$mon" -gt "1" ]; then
		case $1 in
			2)	echo "$eb$wsm3))";;
			1)	echo "$eb$wsm2))";;
			0)	echo "$eb$wsm1))";;
			*)	echo "";;
		esac
	fi
}

workspaces $1
socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r; do 
workspaces $1
done
